# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1
description: |
  Run flutter analyze and tests in CircleCI
display:
  source_url: https://github.com/Sayegh7/flutter-orb
commands: {}
executors: {}
jobs:
  lint:
    description: Run static analysis for Flutter
    docker:
      - image: cirrusci/flutter:stable
    steps:
      - checkout
      - restore_cache:
          keys:
            - dart-dependencies-{{ checksum "pubspec.lock" }}
            - dart-dependencies-
      - run:
          command: flutter pub get
          name: Install Dependencies
      - save_cache:
          key: dart-dependencies-{{ checksum "pubspec.lock" }}
          paths:
            - .dart_tool
      - run:
          command: flutter analyze
          name: Analyze code
    working_directory: ~/repo
  test:
    description: Run tests for Flutter
    docker:
      - image: cirrusci/flutter:stable
    steps:
      - checkout
      - restore_cache:
          keys:
            - dart-dependencies-{{ checksum "pubspec.lock" }}
            - dart-dependencies-
      - run:
          command: flutter pub get
          name: Install Dependencies
      - save_cache:
          key: dart-dependencies-{{ checksum "pubspec.lock" }}
          paths:
            - .dart_tool
      - run:
          command: flutter test
          name: Run tests
    working_directory: ~/repo

workflows:
  flutter:
    jobs:
      - lint
      - test:
          requires:
            - lint